<script>
  import { rul } from "./Ruleset";
  let intro = rul.str("intro");
  console.log(intro);
</script>

{#if intro}
  {@html intro}
{:else}
  <h1>XPedia</h1>
  Autogenerated searcheable HTML reference for OpenXCom games.
  <br />
  Github:
  <a href="https://github.com/baturinsky/xpedia/">
    https://github.com/baturinsky/xpedia/
  </a>
  <br />
  Made by
  <a href="https://github.com/baturinsky">Baturinsky</a>
  with the help of
  <a href="https://openxcom.org/forum/index.php/board,18.0.html">Dioxine</a>
  ,
  <a href="https://github.com/MeridianOXC">Meridian</a>
  and other developers and players of
  <a href="https://openxcom.org/">OpenXCom</a>
  and
  <a href="https://openxcom.org/forum/index.php/board,18.0.html">X-Piratez</a>
  mod.
  <h4>Using</h4>
  Use drop down menu to the left or search form to the right.
  <br />
  If you want to (re)build the xpedia.html for the mod yourself, do the
  following
  <ol>
    <li>
      Download
      <a
        href="https://github.com/baturinsky/xpedia/blob/master/xpedia.zip?raw=true">
        xpedia.zip
      </a>
    </li>
    <li>Copy contents of xpedia.zip to the root directory of the game.</li>
    <li>
      If you have Node.js installed, regardless of OS, run
      <code>node xpedia.js</code>
      . Otherwise, if you are using Windows, run
      <code>xpedia.bat</code>
      .
    </li>
    <li>
      Or if you already has up-to-date xpedia.html you can just open it
      directly.
    </li>
    <li>
      If mod is *not* XPiratez, edit xpedia.bat (or xpeia.js) to change mod's
      name.
    </li>
  </ol>

  <h4>Building from source</h4>

  <pre>
    git clone https://github.com/baturinsky/xpedia/ cd xpedia yarn install npm
    run build
  </pre>

  <h4>Debugging</h4>

  <pre>npm run dev</pre>
  Then open
  <a href="http://localhost:5000">localhost:5000</a>
  <br />
  You will need to generate xpedia.html as above and copy it to
  /public/xpedia.html Also, to have pictures, copy /user directory from the game
  to /public/user
{/if}
